"""Serving schemas for DataPilot Client-Side Prediction API.

All prediction requests and responses are strictly processed inside the client environment.
Zero prediction data is transmitted to the cloud control plane.
"""

from __future__ import annotations

import uuid
from typing import Any, Dict, List, Literal, Optional, Union
from pydantic import BaseModel, ConfigDict, Field


class PredictRequest(BaseModel):
    """Payload for POST /predict.
    
    Accepts either a single dictionary of feature values or a list of feature dictionaries.
    """
    model_config = ConfigDict(extra="allow")

    features: Union[Dict[str, Any], List[Dict[str, Any]]] = Field(
        ...,
        description="Tabular feature dictionary or list of feature dictionaries.",
    )
    request_id: Optional[str] = Field(
        default_factory=lambda: str(uuid.uuid4()),
        description="Optional tracking identifier generated by caller or server.",
    )


class PredictionResult(BaseModel):
    """Result of local model inference returned by POST /predict."""
    prediction_id: str = Field(..., description="Unique ID for this inference call.")
    model_name: str = Field(..., description="Model display name.")
    model_version: str = Field(..., description="Version of the deployed model.")
    predictions: List[Any] = Field(..., description="Array of prediction outcomes.")
    probabilities: Optional[List[Dict[str, float]]] = Field(
        default=None,
        description="Array of class probabilities for classification problems.",
    )
    latency_ms: float = Field(..., description="Local prediction latency in milliseconds.")
    warnings: List[str] = Field(default_factory=list, description="Any warnings encountered.")


class FeatureFieldSchema(BaseModel):
    name: str
    dtype: str = "numeric"  # numeric | categorical | datetime
    nullable: bool = True
    example: Optional[Any] = None


class ModelMetadataResponse(BaseModel):
    """Public model metadata for client inference consumers."""
    model_name: str
    model_version: str
    problem_type: Literal["classification", "regression"]
    target_name: str
    primary_metric: str
    feature_names: List[str]
    feature_schema: List[FeatureFieldSchema]
    classes: Optional[List[Any]] = None
    created_at: str
    deployment_type: str = "local"


class HealthResponse(BaseModel):
    """Health check response."""
    status: Literal["healthy", "ready", "unhealthy"]
    service: str = "datapilot-local-predictor"
    model_loaded: bool
    model_name: Optional[str] = None
    model_version: Optional[str] = None
